version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-deps:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: maven
    directories:
      - "**/*"
    schedule:
      interval: weekly
    groups:
      maven-deps:
        dependency-type: "production"
      maven-dev-deps:
        dependency-type: "development"
    commit-message:
      prefix: "build(deps): "
      prefix-development: "chore(deps): "
    ignore:
      - dependency-name: "org.jruby:jruby"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: bundler
    directories:
      - "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        dependency-type: "production"
      ruby-dev-deps:
        dependency-type: "development"
    commit-message:
      prefix: "build(deps): "
      prefix-development: "chore(deps): "
    ignore:
      - dependency-name: "rails"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "rack"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
