source 'https://rubygems.org'

gem 'rails', '~> 7.2.0'
gem 'rack', '~> 2.2.0'
gem 'i18n', '!= 1.15.0' if RUBY_VERSION.to_f < 3.2

platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter', '~> 72.1'
end