# -*- ruby -*-

require 'rubygems'

spec = Gem::Specification.new do |s|
  s.name        = "sample_jar"
  s.version     = "1.0"
  s.authors     = ["Nick Sieger"]
  s.email       = ["nick@nicksieger.com"]
  s.homepage    = ""
  s.summary     = ""
  s.description = ""
  s.add_runtime_dependency("rubyzip", [">= 0"])
end

task :gemspec do
  File.open('sample_jar.gemspec', 'w') do |f|
    f << spec.to_ruby
  end
end
# vim: syntax=ruby
