# -*- ruby -*-

require 'rubygems'
require 'hoe'

hoe = Hoe.spec 'sample_jar' do |p|
  p.developer('Nick Sieger', 'nick@nicksieger.com')
  p.extra_deps += [["rubyzip", ">= 0"]]
end

task :gemspec do
  File.open('sample_jar.gemspec', 'w') do |f|
    f << hoe.spec.to_ruby
  end
end
# vim: syntax=ruby
